<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        // next() 方法的返回值类似于迭代器， 有一个 done 属性和一个 value 属性。 函数体为空的生成器
        // 函数中间不会停留， 调用一次 next() 就会让生成器到达 done: true 状态。
        (function () {
            function* generatorFn() {}
            let generatorObject = generatorFn();
            console.log(generatorObject); // generatorFn {<suspended>}
            console.log(generatorObject.next()); // { done: true, value: undefined } 
        })();

        (function () {
            // value 属性是生成器函数的返回值，默认值为 undefined，可以通过生成器函数的返回值指定：
            function* generatorFn() {
                return 'foo';
            }
            let generatorObject = generatorFn();
            console.log(generatorObject.next()); // {value: "foo", done: true}
        })();

        // 生成器函数只会在初次调用 next()方法后开始执行，如下所示：
        function* generatorFn1() {
            console.log('foobar');
        }
        // 初次调用生成器函数并不会打印日志
        let generatorObject1 = generatorFn1();
        generatorObject1.next(); // foobar 

        // 生成器函数在遇到 yield关键字之前会正常执行。遇到这个关键字后，执行会停止，函数作用域的状态会被保留。
        (function () {
            function* generatorFn() {
                yield 'foo';
                yield 'bar';
                return 'baz';
            }
            let generatorObject = generatorFn();
            console.log(generatorObject.next()); // { done: false, value: 'foo' }
            console.log(generatorObject.next()); // { done: false, value: 'bar' }
            console.log(generatorObject.next()); // { done: true, value: 'baz' }
        })();

        // yield 关键字还可以作为函数的中间参数使用。上一次让生成器函数暂停的 yield 关键字会接收到传给 next()方法的第一个值。
        (function () {
            function* generatorFn(initial) {
                console.log(initial);
                console.log(yield);
                console.log(yield);
            }
            let generatorObject = generatorFn('foo');
            generatorObject.next('bar'); // foo
            generatorObject.next('baz'); // baz
            generatorObject.next('qux'); // qux
        })();

        (function () {
            // yield 关键字可以同时用于输入和输出， 如下例所示： 相当于 yield "foo"; return yield
            function* generatorFn() {
                return yield 'foo';
            }
            let generatorObject = generatorFn();
            console.log(generatorObject.next()); // { done: false, value: 'foo' }
            console.log(generatorObject.next('bar')); // { done: true, value: 'bar' } 
        })();

        (function () {
            //迭代指定次数:
            function* nTimes(n) {
                for (let i = 0; i < n; ++i) {
                    yield i;
                }
            }
            for (let x of nTimes(3)) {
                console.log(x);
            }
            // 0
            // 1
            // 2 

            function* generatorFn() {
                yield*[1, 2, 3];
            }
            // 等价与 generatorFn：
            // function* generatorFn() {
            // for (const x of [1, 2, 3]) {
            // yield x;
            // }
            // }
            let generatorObject = generatorFn();
            for (const x of generatorFn()) {
                console.log(x);
            }
            // 1
            // 2
            // 3 

            // yield*的返回值是关联迭代器返回 done: true 时的 value 属性。  如果生成器没有return 那么yield* [1,2,3] 整个语句的发回值就是unddefined
        })();

        (function () {
            // 与迭代器类似，生成器也支持“可关闭”的概念。一个实现 Iterator 接口的对象一定有 next()方法，
            // 还有一个可选的 return()方法用于提前终止迭代器。生成器对象除了有这两个方法，还有第三个方法：throw()。
            // return()和 throw()方法都可以用于强制生成器进入关闭状态。
            function* generatorFn() {
                for (const x of [1, 2, 3]) {
                    yield x;
                }
            }
            const g = generatorFn();
            console.log(g); // generatorFn {<suspended>}
            console.log(g.return(4)); // { done: true, value: 4 }
            console.log(g); // generatorFn {<closed>} 

            // throw()方法会在暂停的时候将一个提供的错误注入到生成器对象中。如果错误未被处理，生成器就会关闭：
            // 假如生成器函数内部处理了这个错误，那么生成器就不会关闭，而且还可以恢复执行。错误
            // 处理会跳过对应的 yield，因此在这个例子中会跳过一个值。
            function* generatorFnThrow() {
                for (const x of [1, 2, 3]) {
                    yield x;
                }
            }
            const gg = generatorFnThrow();
            console.log(gg); // generatorFn {<suspended>}
            try {
                gg.throw('foo');
            } catch (e) {
                console.log(e); // foo
            }
            console.log(gg); // generatorFn {<closed>}
        })();
    </script>
</head>

<body>
    <div id="root"></div>
</body>

</html>