<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promise</title>
  </head>

  <body>
    <script>
      // try/catch 不能捕获Promise.reject状态
      (function () {
        let p1 = new Promise((resolve, reject) => resolve());
        setTimeout(console.log, 0, p1); // Promise <resolved>
        let p2 = new Promise((res, rej) => {
          res();
          console.log("resolve 之后继续执行构造函数中的同步代码"); // 打印了
        });
        console.log(p2); // Promsie <resolved>
      })();

      (function () {
        // 期约并非一开始就必须处于待定状态，然后通过执行器函数才能转换为落定状态。通过调用
        // Promise.resolve()静态方法，可以实例化一个解决的期约。下面两个期约实例实际上是一样的：
        let p1 = new Promise((resolve, reject) => resolve());
        let p2 = Promise.resolve();

        // 对这个静态方法而言，如果传入的参数本身是一个期约，那它的行为就类似于一个空包装。会保留传入期约的状态,返回传入的期约 ,这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约。因此，也可能导致不符合预期的行为：
        let p11 = Promise.resolve(new Error("foo"));
        setTimeout(console.log, 0, p11);
        // Promise <resolved>: Error: foo
        // 但是Promise.reject()并没有照搬Promise.resolve()的幂等逻辑。如果给它传一个期约对象，则这个期约会成为它返回的拒绝期约的理由
        let p = Promise.resolve(7);
        setTimeout(console.log, 0, p === Promise.resolve(p));
        // true
        setTimeout(console.log, 0, p === Promise.resolve(Promise.resolve(p)));
        // true !!!

        p.then((res) => {
          // then中onresolve函数返回值会被Promise.resolve()包装
          return Promise.resolve(2 * res);
        })
          .then((res) => {
            // throw new Error('1')
            console.log(res); // 14
          })
          .then((res) => {
            console.log(
              res == void 0,
              "前一个then函数回调没返回值, 会返回Promise.resolve(undefined)"
            );
            return 10;
          })
          .then()
          .then((res) => {
            // throw new Error(2)
            console.log(
              res == 10,
              "前一个then函数中onresolve为空,then会返回Promise.resolve(上一个期约的值)"
            ); // 10
            return new Promise((res) => {
              setTimeout(res, 1000, 100);
            });
          })
          .then((res) => {
            // throw new Error(3)
            console.log(res); // 100
          })
          .catch((err) => {
            console.error(err);
          });

        // 两个p.then 按顺序执行
        p.then((re) => {
          return new Promise((res, rej) => {
            setTimeout(() => {
              res(1);
              // rej('err')
            }, 300);
          }).then((r) => {
            console.log(r); // 1
            throw new Error('bug')
            return r * 2;
          }).catch(err => {
            console.log('inner catch');
            return 11
          })
        })
          .then((res) => {
            console.log(res, 'innercatch如果存在,且有返回值会被Promise.resolve包装');
          })
          .catch((err) => {
            console.error(err);
          });

        // then方法返回一个新的期约实例, 这个新期约实例基于onResovled 处理程序的返回值构建。换句话说，该处理程序的返回值会通过Promise.resolve()包装来生成新期约。如果没有提供这个处理程序，则Promise.resolve()就会包装上一个期约解决之后的值。如果没有显式的返回语句，则Promise.resolve()会包装默认的返回值undefined。

        // onRejected 处理程序也与之类似：onRejected 处理程序返回的值也会被Promise.resolve()包装。乍一看这可能有点违反直觉，但是想一想，onRejected 处理程序的任务不就是捕获异步错误吗？因此，拒绝处理程序在捕获错误后不抛出异常是符合期约的行为，应该返回一个解决期约。

        // Promise.prototype.finally()返回一个新的期约实例, 不同于then()或catch()方式返回的实例, 因为onFinally 被设计为一个状态无关的方法, 当finally回调不返回pending或者reject状态的Promise时 或者回调中抛出异常, 会继承前一个Promise的状态, 返回pending状态的场景并不常见, 因为只要期约一解决，新期约仍然会原样后传初始的期约

        // 如果给期约添加了多个处理程序，当期约状态变化时，相关处理程序会按照添加它们的顺序依次执行。无论是then()、catch()还是finally()添加的处理程序都是如此

        // 拒绝期约与拒绝错误处理  在期约中抛出错误时，因为错误实际上是从消息队列中异步抛出的，所以并不会阻止运行时
      })();
    </script>
    <!-- <script>
      // promise的构造函数是同步执行！！
      // ECMAScript 6 新增的引用类型 Promise，可以通过 new 操作符来实例化。创建新期约时需要传入执行器（executor）函数
      // 作为参数（后面马上会介绍），下面的例子使用了一个空函数对象来应付一下解释器：
      let p = new Promise((resolve, reject) => {
        console.log("promise函数"); //第一个输出  同步的！！
        setTimeout(() => {
          resolve();
        }, 10);
        console.log("promise函数同步的"); //在run之前输出
      });
      setTimeout(console.log, 0, p); // Promise <pending>

      console.log("run");
      (function aa() {
        let p1 = new Promise((resolve, reject) => resolve(1111));
        let p2 = Promise.resolve(1222);
        let p13 = Promise.resolve(1333);
        p1.then((v) => console.log(v));
        p2.then((v) => {
          console.log(v);
          setTimeout(() => {
            console.log("promise then timeout");
          }, 0);
          p13.then((v) => console.log(v));
        });
        console.log("running");

        // Promise then 这个 then()方法接收最多两个参数：onResolved 处理程序和 onRejected 处理程序。处理程序的返回值会通过Promise.resolve()包装来生成新期约。
        // 如果没有显式的返回语句，则 Promise.resolve()会包装默认的返回值 undefined。
      })();

      /**
         * 
         * running
promise.html:23 11
promise.html:25 12
promise.html:29 13
Promise {<pending>}
promise.html:27 promise then timeout
         */

      //  这个静态方法能够包装任何非期约值，包括错误对象，并将其转换为解决的期约。因此，也可能导致不符合预期的行为：
      (function () {
        let p = Promise.resolve(new Error("foo"));
        setTimeout(console.log, 0, p);
        // Promise <resolved>: Error: foo
      })();

      // 异步函数
      // async 关键字用于声明异步函数。这个关键字可以用在函数声明、函数表达式、箭头函数和方法上,异步函数没有return语句时候和普通函数一样
      // 异步函数如果使用 return 关键字返回了值（如果没有 return 则会返回 undefined），这个值会被 Promise.resolve()包装成一个期约对象。
      // 注意观察输出，深入理解宏任务 微任务
      (function () {
        async function foo() {
          console.log(1);
          // 当然，直接返回一个期约对象也是一样的： return Promise.resolve(3);
          return 3;
        }
        // 给返回的期约添加一个解决处理程序
        foo().then(console.log);
        console.log(2);
        // 1`
        // 2
        // 3

        // 使用 await关键字可以暂停异步函数代码的执行，等待期约解决。
        // 要完全理解 await 关键字，必须知道它并非只是等待一个值可用那么简单。JavaScript 运行时在碰
        // 到 await 关键字时，会记录在哪里暂停执行。等到 await 右边的值可用了，JavaScript 运行时会向消息
        // 队列中推送一个任务，这个任务会恢复异步函数的执行。
        // 即使 await 后面跟着一个立即可用的值，函数的其余部分也会被异步求值。
      })();

      (function () {
        console.log(1, "------");
        setTimeout(() => {
          console.log(2);
        }, 0);

        async function fun2() {
          console.log(0);
        }
        async function fun() {
          console.log(4);
          await fun2();
          console.log(5);
        }
        async function fun33() {
          console.log(9);
          return 11;
        }
        new Promise((resolve, reject) => {
          console.log(8);
          let result = 20;
          fun33().then((i) => resolve(i));
        }).then((i) => {
          console.log(i, 13);
        });
        Promise.resolve(10).then((i) => {
          console.log(i);
          setTimeout(() => {
            console.log(7);
          }, 0);
        });
        fun();
        console.log(33);

        // 注意11 13   2 的顺序  只要还有微任务  就不会开始新的宏任务
        // 1 8 9 4 0 33 10 5 11,13 2 7
      })();

      {
        console.log("1");

        setTimeout(function () {
          console.log("2");

          new Promise(function (resolve) {
            console.log("4");
            resolve();
          }).then(function () {
            console.log("5");
            Promise.resolve(0).then((i) => {
              console.log(i);
            });
          });
        });

        new Promise(function (resolve) {
          console.log("7");
          resolve();
        }).then(function () {
          console.log("8");
        });

        setTimeout(function () {
          console.log("9");

          new Promise(function (resolve) {
            console.log("11");
            resolve();
          }).then(function () {
            console.log("12");
          });
        });
        // 执行完所有的微任务,才会执行一个宏任务
        // 1 7 8 2 4 5 0 9 11 12
      }

      // 手写promise   整体还是使用发布订阅的设计模式
      const valueSymbol = Symbol.for("value");
      function MyPromise(exector) {
        const self = this;
        // self[valueSymbol] = null   所有可以是用字符串或者数字的地方都可以使用symbol
        self.value = null;
        self.state = "pending";
        self.reason = null;
        self.onFulfilledCallback = [];
        self.onRejectCallback = [];

        function resolve(value) {
          if (self.state == "pending") {
            // self[valueSymbol] = value
            self.value = value;
            self.state = "fulfilled";
            self.onFulfilledCallback.forEach((i) => i(value));
          }
        }

        function reject(reason) {
          if (self.state == "pending") {
            self.state = "rejected";
            self.reason = reason;
            self.onRejectCallback.forEach((i) => i(value));
          }
        }

        try {
          exector(resolve, reject);
        } catch (error) {
          reject(error);
        }
      }

      MyPromise.prototype.then = function (onresolved, onrejected) {
        const self = this;
        onresolved =
          typeof onresolved == "function"
            ? onresolved
            : function (data) {
                return data;
              };
        onrejected =
          typeof onrejected == "function"
            ? onrejected
            : function (err) {
                throw err;
              };

        if (self.state == "fulfilled") {
          // console.log(self[valueSymbol], "symbol")
          return new MyPromise((resolve, reject) => {
            try {
              const x = onresolved(self.value);
              if (x instanceof MyPromise) {
                x.then(resolve, reject);
              } else {
                resolve(x);
              }
            } catch (error) {
              reject(error);
            }
          });
        }

        if (self.state == "rejected") {
          return new MyPromise((resolve, reject) => {
            try {
              const x = onrejected(self.value);
              if (x instanceof MyPromise) {
                x.then(resolve, reject);
              } else {
                resolve(x);
              }
            } catch (error) {
              reject(error);
            }
          });
        }

        // 处理Promise里面如果是异步的情况
        if (self.state == "pending") {
          return new MyPromise((resolve, reject) => {
            self.onFulfilledCallback.push(() => {
              let x = onresolved(self.value);
              if (x instanceof Promise) {
                x.then(resolve, reject);
              } else {
                resolve(x);
              }
            });
            self.onRejectedCallback.push(() => {
              let x = onRejected(self.reason);
              if (x instanceof Promise) {
                x.then(resolve, reject);
              } else {
                resolve(x);
              }
            });
          });
        }
      };

      MyPromise.prototype.all = function (promiseArr) {
        let result = [];
        let count = 0;
        return new Promise((resolve, reject) => {
          promiseArr
            .forEach((promiseItem, index) => {
              promiseItem.then((value) => {
                result[index] = value;
                count++;
                if (conut === promiseArr.length) {
                  resolve(reslut);
                }
              });
            })
            .catch((e) => {
              reject(e);
            });
        });
      };

      // Test
      console.log("test-----------");
      const P1 = new MyPromise((resolve, reject) => {
        resolve("121");
      });
      P1.then(function (value) {
        console.log(value, "----");
        return new MyPromise((res, rej) => {
          res("1111111");
        });
      }).then((value) => {
        console.log(value);
      });
      // P1.then(1212)
      console.log(P1);
    </script> -->

    <script>
      // (function () {
      //   let p1 = new Promise((res, rej) => {
      //     setTimeout(() => {
      //       res("11");
      //     }, 3000);
      //   });
      //   p1.then((res) => {
      //     console.log("p1 then1", res);
      //   })
      //     .then((res) => {
      //       console.log("p1 then2", res);
      //     })
      //     .then((res) => {
      //       console.log("p1 then3", res);
      //     });
      //   // p1 then1 11
      //   // p1 then2 undefined
      //   // p1 then3 undefined
      // })();

      // (function () {
      //   let p1 = new Promise((res, rej) => {
      //     setTimeout(() => {
      //       res("11");
      //     }, 3000);
      //   });
      //   p1.then((res) => {
      //     console.log("p1 then1", res);
      //     return 22
      //   })
      //     .then((res) => {
      //       console.log("p1 then2", res);
      //       return 33
      //     })
      //     .then((res) => {
      //       console.log("p1 then3", res);
      //     });
      //   // p1 then1 11
      //   // p1 then2 22
      //   // p1 then3 33
      // })();

      (function () {
        let p1 = new Promise((res, rej) => {
          setTimeout(() => {
            res("11");
          }, 3000);
        });
        p1.then((res) => {
          console.log("p1 then1", res);
          return new Promise((res) => {
            setTimeout(() => {
              res("kakaka");
            }, 200);
          });
        })
          .then((res) => {
            console.log("p1 then2", res);
            return 33;
          })
          .then((res) => {
            console.log("p1 then3", res);
          });
        // p1 then1 11
        // p1 then2 kakaka
        // p1 then3 33
      })();

      console.log("------------");
      function p1(params) {
        console.log("p1 params", params);
        return new Promise((res, rej) => {
          setTimeout(() => {
            res("p1 resolve");
          }, 500);
        });
      }
      function p2(params) {
        return new Promise((res, rej) => {
          setTimeout(() => {
            console.log("p2 resolve");
            res("p2 resolve");
          }, 500);
        });
      }
      // 函数返回promise
      function login(params) {
        return p1("p1").then((res) => {
          console.log("p1 then", res);
          return p2().then((r) => {
            console.log("p2 then", r);
            return r;
          });
        });
      }
      login({ name: "wang" }).then((res) => {
        console.log("login then", res);
      });
      // p1 params p1
      // p1 then p1 resolve
      // p2 resolve
      // p2 then p2 resolve
      // login then p2 resolve
    </script>

    <script>
      // trycatch捕获不了异步代码 可以使用promise.catch 或者使用try{ await }catch
      try {
        new Promise((res, rej) => {
          setTimeout(() => {
            rej("custom error")
          }, 1000);
        })
      } catch (error) {
        console.error(error);
      }
    </script>
  </body>
</html>
